### ISSUE TITLE
bug fix 

### ISSUE THREAD

**Issue by allonli** [anzhihe/Efficient-office#2]
这个workflow里，如“国”不能查询，原因是没有去掉换行符。
```soup = BeautifulSoup(resp.content, "html.parser")```
下面代码已修复，请更新吧。因为这种格式不方便发PR，就这样吧。
```soup = BeautifulSoup(resp.content.replace("'u'\n'", ' ').replace('\r', '').replace('\n',''), "html.parser")```

**Comment by anzhihe** [comment]
已修复，多谢指导
